### ISSUE TITLE
Getting quota exceeded error when tried to access

### ISSUE THREAD

**Issue by sndpwrites** [cubbic/youtubeRandomVideoNodeJs#1]
The following is the error message I get :
err {
  "error": {
    "code": 403,
    "message": "The request cannot be completed because you have exceeded your \u003ca href=\"/youtube/v3/getting-started#quota\"\u003equota\u003c/a\u003e.",
    "errors": [
      {
        "message": "The request cannot be completed because you have exceeded your \u003ca href=\"/youtube/v3/getting-started#quota\"\u003equota\u003c/a\u003e.",
        "domain": "youtube.quota",
        "reason": "quotaExceeded"
      }
    ]
  }
}

**Comment by macedonga** [comment]
Your API key has a maximum number of requests you can do with it.
